package ru.yandex.practicum.filmorate.storage.dao.impl;

import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.BeanPropertySqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;
import ru.yandex.practicum.filmorate.exception.DataBaseResponseException;
import ru.yandex.practicum.filmorate.model.User;
import ru.yandex.practicum.filmorate.storage.UserStorage;

import java.util.*;

import static ru.yandex.practicum.filmorate.Constants.USER_ROW_MAPPER;

@Repository("userDbStorage")
public class UserDbStorage implements UserStorage {

    private final JdbcTemplate jdbcTemplate;
    private final NamedParameterJdbcTemplate namedParameterJdbcTemplate;
    private String sqlQuery;

    public UserDbStorage(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(jdbcTemplate);
    }

    @Override
    public User save(User user) {
        if (user.getId() == 0) {
            sqlQuery = "INSERT INTO users (login, email, name, birthday) VALUES (:login, :email, :name, :birthday)";
        } else {
            sqlQuery = "UPDATE users SET user_id = :id, login = :login, name = :name, birthday = :birthday " +
                    "WHERE USER_ID = :id";
        }
        SqlParameterSource userParams = new BeanPropertySqlParameterSource(user);
        KeyHolder keyHolder = new GeneratedKeyHolder();
        int rowNums = namedParameterJdbcTemplate.update(sqlQuery, userParams, keyHolder);
         if (rowNums == 0) {
             throw new DataBaseResponseException(
                     String.format("При попытке добавить пользователя с id=%d произошла ошибка", user.getId())
             );
         } else if (user.getId() == 0) {
             long autoGeneratedKey = Objects.requireNonNull(keyHolder.getKey()).longValue();
             user.setId(autoGeneratedKey);
         }
        return user;
    }

    @Override
    public Optional<User> findById(long id) {
        sqlQuery = "SELECT * FROM users WHERE user_id = ?";
        try {
            return Optional.ofNullable(jdbcTemplate.queryForObject(sqlQuery, USER_ROW_MAPPER, id));
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<User> findAll() {
        sqlQuery = "SELECT * FROM users";
        try {
            return jdbcTemplate.query(sqlQuery, USER_ROW_MAPPER);
        } catch (EmptyResultDataAccessException e) {
            return Collections.emptyList();
        }
    }

    @Override
    public List<User> findAllById(Iterable<Long> ids) {
        sqlQuery = "SELECT * FROM users WHERE user_id IN (?)";
        try {
            return jdbcTemplate.query(sqlQuery, USER_ROW_MAPPER, ids);
        } catch (EmptyResultDataAccessException e) {
            return Collections.emptyList();
        }
    }

    public void deleteById(long id) {
        sqlQuery = "DELETE FROM users WHERE user_id = ?";
        int rowNums = jdbcTemplate.update(sqlQuery, id);
        if (rowNums == 0) {
            throw new DataBaseResponseException("User not found: id=" + id);
        }
    }

    public void deleteAllById(Iterable<Long> ids) {
        sqlQuery = "DELETE FROM users WHERE user_id IN (?)";
        jdbcTemplate.update(sqlQuery, ids);
    }

    public void deleteAll(Iterable<User> users) {
        LinkedList<Long> ids = new LinkedList<>();
        for (User user : users) {
            ids.addLast(user.getId());
        }
        deleteAllById(ids);
    }

    @Override
    public boolean existsById(long id) {
        return findById(id).isPresent();
    }

}
